#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 8 12:01:07 2024

@author: davidmenezes
"""

# =============================================================================
# ADDITIONAL NOTES + COMMENTS
# Hey David. I just wanted to check in, I think when using np.random.normal() 
# the scale you’ll want to use it the np.std(flux - modelflux)
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
import os
import sys

from astropy.io import fits
import scipy
from scipy import integrate

# =============================================================================
# import glob
# import matplotlib as mpl
# import scipy
# from astropy.convolution import convolve
# from astropy.convolution import Gaussian1DKernel
# from astropy.convolution import Box1DKernel
# from astropy.io import fits
# from scipy.optimize import curve_fit as curve_fit
# from matplotlib import rcParams
# from scipy.signal import argrelmin
# from astropy.io import ascii
# from matplotlib.gridspec import GridSpec
# =============================================================================

directory = os.listdir('/Users/davidmenezes/Downloads/2023-24 Research/rm101/Main/')
direc = '/Users/davidmenezes/Downloads/2023-24 Research/rm101/Main/'
file = '/Users/davidmenezes/Downloads/2023-24 Research/rm101/Main/spec-15171-59252-4350974392.fits'
with fits.open(file) as hdu:
    hdu = fits.open(file)
    data1 = hdu[1].data
    data2 = hdu[2].data
    header1 = hdu[1].header
    header2 = hdu[2].header
    
    IVAR = data1["IVAR"]

#Switch key names + Switch wavelength to restframe (IF ON MACBOOK CHANGE TO DESKTOP NOT DOWNLOADS)
def read_spectrum(file):
    with fits.open(file) as hdu:
        data1 = hdu[1].data
        data2 = hdu[2].data

        IVAR = data1["IVAR"]
        flux = data1["FLUX"]
        mjd = data2['MJD']
        wav = 10**(data1["LOGLAM"])
        z = data2["z"][0]
        restwavelength = wav / (1 + z)

        # === NEW: Mask based on IVAR == 0
        zero_ivar_mask = IVAR == 0

        # === Flux mask: filter out values below some threshold, e.g., flux > -1e5 (change as needed)
        flux_mask = np.isfinite(flux) & (flux > -1e5) & (flux < 1e5)  # conservative range

        # === Compute NMAD uncertainty
        def nmad(arr):
            return 1.4826 * np.median(np.abs(arr - np.median(arr)))
        
        flux_nmad = nmad(flux[flux_mask]) if np.any(flux_mask) else np.nan
        uncertainty = np.full_like(flux, flux_nmad)

        # Final mask: only include good flux, non-zero IVAR, and finite uncertainty
        mask = flux_mask & np.isfinite(uncertainty) & (IVAR > 0)
        
        #Original Return Statement #return wav[mask], flux[mask], uncertainty[mask], restwavelength[mask], mjd, z, zero_ivar_mask

        return wav[mask], flux[mask], uncertainty[mask], restwavelength[mask], mjd, z

#filter around H-beta (width = 1370 angstroms)
def hbeta_filter(wavelength, width=1370):
    center = 4861
    filter_mask = (wavelength >= (center - width / 2)) & (wavelength <= (center + width / 2))
    return filter_mask


#G-filter
def g_filter(wavelength):
    center = 4861
    width = 1370
    filter_mask = (wavelength >= (center - width / 2)) & (wavelength <= (center + width / 2))
    return filter_mask


#Monte Carlo simulation for uncertainty
def monte_carlo_photometry(wavelength, flux, filter_mask, uncertainty, n_iterations=20):
    fluxes = []
    for _ in range(n_iterations):
        perturbed_flux = np.random.normal(flux, uncertainty)
        flux_in_filter = perturbed_flux[filter_mask]
        fluxes.append(integrate.simpson(flux_in_filter, x = wavelength[filter_mask]))
    return fluxes

#Missing I-VAR issue fix


#perturbed spectra plot
def plot_perturbed_spectra(wavelength, flux, perturbed_flux):
    plt.figure(figsize=(10, 6))
    plt.plot(wavelength, flux, label='Original Spectrum', color='blue')
    plt.plot(wavelength, perturbed_flux, label='Perturbed Spectrum', color='red', alpha=0.7)
    plt.xlabel('Wavelength (Angstroms)')
    plt.ylabel('Flux')
    plt.legend()
    plt.show()


#histogram
def plot_flux_histogram(fluxes):
    plt.figure(figsize=(8, 6))
    plt.hist(fluxes, bins=30, color='grey', alpha=0.7)
    plt.xlabel('Flux ($10^{-17}$ erg/s/cm$^2$/Ang)') 
    plt.ylabel('Frequency')
    plt.title('Histogram of Flux Measurements')
    plt.show()


lcflux = []
lcerr = []
mjdfinal = []


for ep in os.listdir(direc):
    file_path = os.path.join(direc, ep)
    if os.path.isfile(file_path):
        wav, flux, uncertainty, restwavelength, mjd, z = read_spectrum(file_path)
        # read_spectrum(file_path)
        filt = hbeta_filter(wav)
        fluxes_mc = monte_carlo_photometry(wav, flux, filt, uncertainty)
        fluxes_mc = np.asarray(fluxes_mc)
        fluxes_mc = fluxes_mc/1370
        lcflux.append(np.median(fluxes_mc))
        lcerr.append(np.std(fluxes_mc))
        mjdfinal.append(mjd)
        
        # plot_flux_histogram(fluxes_mc)
        
plot_flux_histogram(fluxes_mc)
plt.figure(figsize=(12, 6))
plt.xlabel("MJD") 
plt.ylabel('Flux ($10^{-17}$ erg/s/cm$^2$/Ang)')
plt.title('Synthetic Photometry Hbeta Light Curve')
plt.errorbar(mjdfinal, lcflux, yerr = lcerr, fmt = 'o', color = "red")
# Save these into a DAT file 
plt.legend()
plt.show()
