#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 8 12:01:07 2024

@author: davidmenezes
"""

# =============================================================================
# ADDITIONAL NOTES + COMMENTS
# Hey David. I just wanted to check in, I think when using np.random.normal() 
# the scale you’ll want to use it the np.std(flux - modelflux)
# =============================================================================

import numpy as np
import matplotlib.pyplot as plt
import os

from astropy.io import fits
import scipy
from scipy import integrate

# =============================================================================
# import glob
# import matplotlib as mpl
# import scipy
# from astropy.convolution import convolve
# from astropy.convolution import Gaussian1DKernel
# from astropy.convolution import Box1DKernel
# from astropy.io import fits
# from scipy.optimize import curve_fit as curve_fit
# from matplotlib import rcParams
# from scipy.signal import argrelmin
# from astropy.io import ascii
# from matplotlib.gridspec import GridSpec
# =============================================================================

directory = os.listdir('/Users/davidmenezes/Downloads/2023-24 Research/rm101/Main/')
direc = '/Users/davidmenezes/Downloads/2023-24 Research/rm101/Main/'


#Switch key names + Switch wavelength to restframe (IF ON MACBOOK CHANGE TO DESKTOP NOT DOWNLOADS)
def read_spectrum(file):
    with fits.open(file) as hdu:
        hdu = fits.open(file)
        data1 = hdu[1].data
        data2 = hdu[2].data
        header1 = hdu[1].header
        header2 = hdu[2].header
        
        IVAR = data1["IVAR"]
        flux = data1["FLUX"]
        mjd = data2['MJD']
        wav = 10**(data1["LOGLAM"])
        z = data2["z"][0]
        restwavelength = wav/(1+z)
        
        with np.errstate(divide='ignore', invalid='ignore'):
            uncertainty = np.where(IVAR > 0, 1 / np.sqrt(IVAR), np.inf)
        
        # Filtering: Mask for valid entries
        mask = (IVAR > 0) & np.isfinite(flux) & np.isfinite(uncertainty)

        # Apply mask to variables
        wav = wav[mask]
        flux = flux[mask]
        uncertainty = uncertainty[mask]
        restwavelength = restwavelength[mask]
        
        
    return wav, flux, uncertainty, restwavelength, mjd, z

#filter around H-beta (width = 1370 angstroms)
def hbeta_filter(wavelength):
    center = 4861
    width = 1370
    filter_mask = (wavelength >= (center - width / 2)) & (wavelength <= (center + width / 2))
    return filter_mask



#Monte Carlo simulation for uncertainty
def monte_carlo_photometry(wavelength, flux, filter_mask, uncertainty, n_iterations=500):
    fluxes = []
    for _ in range(n_iterations):
        perturbed_flux = np.random.normal(flux, uncertainty)
        flux_in_filter = perturbed_flux[filter_mask]
        fluxes.append(integrate.simpson(flux_in_filter, x = wavelength[filter_mask]))
    return fluxes



#perturbed spectra plot
def plot_perturbed_spectra(wavelength, flux, perturbed_flux):
    plt.figure(figsize=(10, 6))
    plt.plot(wavelength, flux, label='Original Spectrum', color='blue')
    plt.plot(wavelength, perturbed_flux, label='Perturbed Spectrum', color='red', alpha=0.7)
    plt.xlabel('Wavelength (Angstroms)')
    plt.ylabel('Flux')
    plt.legend()
    plt.show()


def plot_flux_histogram(fluxes):
    plt.figure(figsize=(8, 6))
    plt.hist(fluxes, bins=30, color='grey', alpha=0.7)
    plt.xlabel('Flux') #units
    plt.ylabel('Frequency')
    plt.title('Histogram of Flux Measurements')
    plt.show()



    
for ep in direc:
    read_spectrum(ep)
    filt = hbeta_filter(wav)
    fluxes_mc = monte_carlo_photometry(wav, flux, filt, uncertainty)
    plot_flux_histogram(fluxes_mc)

